language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ayodejialabi/reactprojectdevops -f Dockerfile.dev .

script:
  - docker run ayodejialabi/reactprojectdevops npm run test -- --coverage