version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /usr/applications/reactfrontendjs/node_modules
      - .:/usr/applications/reactfrontendjs/
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/applications/reactfrontendjs/node_modules
      - .:/usr/applications/reactfrontendjs/
    command: ["npm","run","test"]

